# Generated by Django 3.2.20 on 2023-07-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Newsletter',
        ),
    ]
