# Generated by Django 3.2.20 on 2023-07-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_signup_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='name',
            new_name='full_name',
        ),
    ]
