# Generated by Django 3.2.20 on 2023-07-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_number',
        ),
    ]
