# Generated by Django 3.2.20 on 2023-07-25 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_reservation_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('Canceled', 'Canceled')], default=('New', 'New'), max_length=15),
        ),
    ]
