# Generated by Django 3.2.20 on 2023-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20230725_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('Canceled', 'Canceled')], default=('New', 'New'), max_length=15),
        ),
    ]
