# Generated by Django 3.2.20 on 2023-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230712_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.Size'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='topping',
        ),
        migrations.AddField(
            model_name='product',
            name='topping',
            field=models.ManyToManyField(to='products.Topping'),
        ),
    ]
