# Generated by Django 3.2.20 on 2023-07-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230718_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
