# Generated by Django 3.2.20 on 2023-07-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230724_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
